---
token: tokentokentoken

prefix: "!"

bot_channel: 1234
testing_channel: 1234

roles:
  god: 1111
  admin: 2222
  botadmin: 3333
  disciple: 4444

class_categories:
  100: 1111
  200: 2222
  300: 3333
  400: 4444
  500: 5555

colors:
  success: 4CAF50
  error: f44336
  info: 2196F3
  warn: FFC107
